### ISSUE TITLE
overriding variables in `pav run` doesn't really work

### ISSUE THREAD

**Issue by francinelapid** [hpc/pavilion2#114]
I think I originally opened this because `pav run -c slurm.num_nodes=<etc>` didn't work, but I think it works now...

**Comment by francinelapid** [comment]
Sample case 1:

```
variables:
    to: 10

run:
    timeout: "{{to}}"
```

`pav run test -c variables.to=20` times out after 2 seconds, not 20!
