### ISSUE TITLE
Table Result Parser

### ISSUE THREAD

**Issue by Paul-Ferrell** [hpc/pavilion2#126]
Has trouble parsing this table:
```
#----------------------------------------------------------------
# Benchmarking Alltoall
# #processes = 3012
#----------------------------------------------------------------
       #bytes #repetitions  t_min[usec]  t_max[usec]  t_avg[usec]
            1         1000       523.93       682.30       554.28
            2         1000       591.19       761.83       633.74
            4         1000       617.36       724.13       642.48
            8         1000       695.25       848.97       741.85
```

With this config:
```
        table:
            key: foo
            col_num: 5
            col_names: ['#bytes', '#repetitions', 't_min[usec]', 't_max[usec]', 't_avg[usec]']
            has_header: True
```
results in:
```
  'foo': {'#repetitions': {'#': 'All',
                           '#bytes': '#repetitions',
                           '1': '1000',
                           '2': '1000',
                           '4': '1000',
                           '8': '1000'},
          't_avg[usec]': {'#': 'MPI_Finalize',
                          '#bytes': 't_avg[usec]',
                          '1': '554.28',
                          '2': '633.74',
                          '4': '642.48',
                          '8': '741.85'},
          't_max[usec]': {'#': 'entering',
                          '#bytes': 't_max[usec]',
                          '1': '682.30',
                          '2': '761.83',
                          '4': '724.13',
                          '8': '848.97'},
          't_min[usec]': {'#': 'processes',
                          '#bytes': 't_min[usec]',
                          '1': '523.93',
                          '2': '591.19',
                          '4': '617.36',
                          '8': '695.25'}},
```

**Comment by francinelapid** [comment]
This worked for me:
```
    results:
        table:
            key: hpcg_table
            col_num: 5
            col_names: ['#bytes', '#repetitions', 't_min[usec]', 't_max[usec]', 't_avg[usec]']
            has_header: True
            delimiter: '\\s\\s+'
```
