### ISSUE TITLE
Add 'name_list' to 'per_file' key.

### ISSUE THREAD

**Issue by Paul-Ferrell** [hpc/pavilion2#136]
Sometimes you just want a list of what files exist or match a given results parser.

```yaml

results:
  # This will match each file regardless of contents. 
  const:
    key: failures
    files: *.fail
    const: 'failed'
    per_file: 'name_list'
```

Given a build directory with 'foo.fail', 'bar.fail', we would get results with:
```yaml
'failures': ['foo', 'bar']
```
