### ISSUE TITLE
Add a 'files' directive, to directly define files in the config.

### ISSUE THREAD

**Issue by Paul-Ferrell** [hpc/pavilion2#140]
This is for dynamically creating small files on the fly. 

```yaml
mytest:
  variables:
    xdim: 104
    ydim: 104
    zdim: 104
    runtime: 10
  build:
    files:
      'datfiles/hpgc.dat':
         - 'HPCG benchmark input file'
         - 'Sandia National Laboratories; University of Tennessee, Knoxville'
         - '{{xdim}} {{ydim}} {{zdim}}'
         - '{{runtime}}'
```

 - The file path relative to the build directory.
 - The path must be within the build directory.
 - Directories in the path should be created by Pavilion, if necessary.
 - The generated file must be included in the build hash.
 - The 'files' directive is allowed in both the 'build' and 'run' sections.
 - If this is in the 'build' section, no deferred variables are allowed.
