### ISSUE TITLE
Permute_on values should check for sub_variables (and tell the user that's not ok)

### ISSUE THREAD

**Issue by Paul-Ferrell** [hpc/pavilion2#185]
```yaml

mytest:
  permute_on: foo.bar
  variables:
    foo:
      - {bar: 1, baz:2}
      - {bar: 3, baz:4}
```

The user should just put in `permute_on: foo`. `foo.bar` should result in an error.
