### ISSUE TITLE
permute_on variables should be displayed in `pav status` and the results dictionary

### ISSUE THREAD

**Issue by nicholas-sly** [hpc/pavilion2#186]
`pav status` should have another column (optionally under the verbose flag) that lists which variables that a test is set to `permute_on`.  This will rely on the variables over which a test permutes be named in an informative way to make this useful, but that seems unenforceable.

Likewise, the `permute_on` variable/values should be saved in the results dictionary for reference.  I'd suggest a format like:
A config containing:
```yaml
...
  permute_on: var1, var2
  variables:
    var1:
    - { subvar1: subval1, subvar2: subval2 }
    - { subvar1: subval11, subvar2: subval12}
    - { subvar1: subval21, subvar2: subval22}
    var2:
    - { subvar3: subval3, subvar4: subval4 }
    - { subvar3: subval13, subvar4: subval14 }
...
```
will produce a results.json entry that looks like:
```
{...,
 'permute_on':
 {
  {'var1':
   {'subvar1': 'subval1',
    'subvar2': 'subvval2'
   },
   'var2':
   {'subvar3': 'subval3',
    'subvar4': 'subval4'
   }
  },
 ...
}
```
