### ISSUE TITLE
Math in Pav test configuration strings

### ISSUE THREAD

**Issue by Paul-Ferrell** [hpc/pavilion2#192]
We need to allow for various sorts of math in pavilion test config strings. I'll need to switch config string parsing to an actual LALR parser to enable this, but that needs to happen anyway. This basic functionality can probably overlap perfectly with result analysis.

Requirements:
 - Conversion to int/float
 - Basic math operations (+ - * / ^ ())
 - Math functions (sqrt, log, etc) as plugins.

**Comment by Paul-Ferrell** [comment]
```yaml
mytest: 
  variables:
    # Basic Arithmetic
    speed: "{{(var.a + 1)*(var.b - 2)^2}}"
    num_nodes: "{{sched.nodes*0.9}}"
    # A variable escape no longer actually needs to contain a variable.
    run_seconds: "{{60/4}}"
    # Integer divide
    use_cpus: "{{test_cpus//4}}"
    # Function calls are all plugins.
    
```
