### ISSUE TITLE
Make Pavilion Spack Aware

### ISSUE THREAD

**Issue by Paul-Ferrell** [hpc/pavilion2#2]
- Add a Spack configuration section
   - Point to a spack environment
   - Spack env to enable
   - Spack build directories?

# Build
 - config changes can include a spack build spec.
 - Spack 'modules' to load

# Run 
 - Should include built spec in environment automatically
 - Spack run environment loading

**Comment by francinelapid** [comment]
```yaml
build:
    spack:
        install: <package_name>
        dependencies: True/False
```
