### ISSUE TITLE
A subtitle should be auto-generated for permuted tests.

### ISSUE THREAD

**Issue by Paul-Ferrell** [hpc/pavilion2#209]
Permuted tests should automatically get a subtitle, if one isn't defined, based on permuted variables.

**Comment by Paul-Ferrell** [comment]
```
mytest: 
  permute_on: [foo, bar]
  variables:
    foo: [hello, world]
    bar: 
      - {'a': 'some long string', 'b': '5'}
      - {'b': '400000', 'a': 'shorty'}
```
