### ISSUE TITLE
Extendable commands

### ISSUE THREAD

**Issue by Paul-Ferrell** [hpc/pavilion2#217]
Add ability to extend commands. 

Options:
1. 
```yaml
mytest:
  inherits_from: foo
  run: 
    cmds+: ['another command']
```
