### ISSUE TITLE
bug: empty regex from result parser will pass

### ISSUE THREAD

**Issue by j-ogas** [hpc/pavilion2#236]
The following block results in a test that always succeeds regardless of whether or not the regex returns anything. It should fail if the regex returns nothing.

```
    results:
        regex:
            - key: result
              regex: 'memory:([0-9]+)'
              expected: "{{overcommit.value}}"
              files: "*.{{overcommit.status}}.out"
              per_file: all
```
