### ISSUE TITLE
Command Inheritance Extend

### ISSUE THREAD

**Issue by Paul-Ferrell** [hpc/pavilion2#267]
Make it so that you can extend (and maybe prefix) pavilion commands when using inheritance, rather than just completely overwriting the existing commands.

## Option 1
```yaml

_base:
  run:
    cmds:
      - echo 'hello, punks'

mytest:
  inherits_from: _base
  run:
    cmds_prepend: 
      - echo 'I happen first.'
    cmds_extend:
      - echo 'I happen last.'
```

## Option 2
```yaml
# Using the same base as above.

mytest2:
  inherits_from_base:
  run:
    # Options are append | prepend | replace
    # replace is default.
    cmd_action: append  # The name of this is debatable.
    cmds:
      - echo 'I happen last.'
```

## Option 3
Add '@some_var' syntax to insert a list of variables into place. 

Questions.
 - Complex variables?
