### ISSUE TITLE
Test Series Files

### ISSUE THREAD

**Issue by Paul-Ferrell** [hpc/pavilion2#27]
# Problem
This already exists in a limited extend under the pavilion -f option, but needs to be extended and reworked. 

Requirements:
 - Built in modes/overrides
 - Hierarchical 
  - Tests should be able to form a dependency tree and have an implied order. 
  - A failed test should cancel any dependent tests. 

# Solution?
The series file would work as follows:
```yaml
# Putting the test series under a separate key allows for high level 
# options like 'ordered' below.
series:
  # Each test is denoted by the name as a mapping key. 
  first_test: 
    # Extra modes to run this test under.
    modes: [postDST]
    # Only run this test if the given system variable matchs (or contain)
    # the given value. The value can be a plain string, glob, or list of those.
    only_if:
      sys_name: lightning
    # The opposite of only_if - Run the test if non of these match.
    not_if:
      sys_network: purple

  # The options are all optional; You can just give a test as a lonely key.
  second_test:
  
  # Test names can include test variant names.
  third_test.sub_test:
    # This test will only be run if first_test passes.
    depends_on: first_test
    
# Tests are by default not ordered (except where depends_on is specified). 
# When set to true, ordered causes each test to depend on the one 
# before it in the above list. This is overridden by 'depends_on'. 
ordered: true
# Modes to apply to all tests.
modes: 
```
   
### Ordering
Test ordering should work as follows. Each test can depend on one or more other tests in the series. If the global ordered setting is true, then each test will automatically depend on the prior test in the series. Cycles are checked for automatically.

Dependent tests will only run if all parent tests complete and with a PASS result.

Tests that have not yet started should be in a new PENDING state, with a description stating which test # (and it's name) that it is waiting on. When a test has an error or a FAIL result, it will be put into the ABORTED state with an appropriate description. 

### Skipping Tests
Series files provide a mechanism for skipping tests based on variable values. Skipped test objects are still created and tracked along with their run directories, but instead of running they are simply assigned the 'SKIPPED' status. If a test is SKIPPED, all of its dependent tests are SKIPPED as well.

#### only_if
Each test in a series has an `only_if` attribute that contains another mapping. The key of this mapping is a variable name that must be resolvable from that test's variable manager. The value is a list of (or single) globs. The clause is true iff the value of the key matches any of the given globs.

The test is run only if __all__ of the `only_if` clauses are true, it is otherwise SKIPPED.

#### not_if
The `not_if` attribute is exactly like the `only_if` clause in terms of format, but the final logic is inverted. Like `only_if` each clause is true if the key matches `any` of the values, but the test is SKIPPED if any of the clauses are true.
