### ISSUE TITLE
Listed evaluations

### ISSUE THREAD

**Issue by Paul-Ferrell** [hpc/pavilion2#270]
```yaml
mytest:
  evaluate_results:
    'n.*.normalized_speed': 'this.speed/avg(n.*.speed)'
```

- This would add a 'normalized_speed' key under each value of key 'n'. 
- The 'this' variable is the structure at 'n.key'; basically, the data for the specific key we're evaluating.
- As shown, all other result keys are still available.

## Value dependencies
This makes value dependency checks significantly more difficult.
