### ISSUE TITLE
Add a run/build option to specify a different file to follow for run/build timeouts.

### ISSUE THREAD

**Issue by Paul-Ferrell** [hpc/pavilion2#292]
```yaml

mytest:
  run:
    # mytest sends output to mytest.out
    cmds: '{{test_cmd}} ./mytest'
    timeout_file: mytest.out
```

Unlike with the run log, 'mytest.out' need not exist the entire time.
