### ISSUE TITLE
Improved result parsing options.

### ISSUE THREAD

**Issue by Paul-Ferrell** [hpc/pavilion2#306]
1. Make names that start with an underbar 'hidden'. Delete such items after the evaluation step.
2. Add a new 'action': multi
    a. This should always expect a dictionary from the result parser, and store the matched keys directly in the results.
    b. This should still work with all of the 'per_file' settings.
3. Upgrade the regex parser.
    a. Add a 'keys' element. Store the matched 'group' items in a dict by the keys. 
    b. More than one matching group should require keys, a single matching group should just return the match group value (and no keys allowed), and no group should return the full matched string. 
    c. Add a 'match_before' argument. Only matches that are followed by lines that match each of the listed regexes count as a match.
    d. Add a 'match_after' argument. Same as above, but only keep matches preceded by the items.
4. Type auto conversion on all parsed results. Add an 'autotype' field that defaults to 'True' for each result parser. Run all parsed     
    results through the type auto-converter by default.

Example:

```yaml
foo:
  result_parse:
    regex:
      # This key won't exist in the result, both because we're going to 'store_multi', 
      # and because it starts with an underscore.
      _test_results: 
        action: store_multi
        match_after: 
           - '^Speed\s+Score\s+'
           - '^-+'
        regex: '^(\S+)\s+(\S+)\s+\S+\s+(\S+)'
        keys: ['speed', 'score', 'adj_score']
```

Given input like:
```
Running the test...
yada yada yada

Finished.
42     12    19   35

Speed       Score   Steptime      Adjusted
-------------------------------------------------------
34.2          45.18    3                  3.12
17  2  8 3
```

We would end up with results that look like:
```json
{
 "name": "foo",
 "speed": 34.2,
 "score": 45.18,
 "adj_score": 3.12,
 "etc...": "",
}
```
Note that the values are auto-converted.
