### ISSUE TITLE
Seperated Values Result Parser

### ISSUE THREAD

**Issue by Paul-Ferrell** [hpc/pavilion2#307]
See #306 

 - Should include `match_after`, `match_before` options. 
 - The seperator should default to whitespace, but be plain text. 
 - All whitespace will be automatically stripped. 
 - No special handling of the '_' should be necessary, as those are deleted automatically.

Note that this isn't hugely different from the regex parser, but simplifies a common case.

```yaml
foo:
  result_parse:
    sep_vals:
      match_after: 
        - '^Speed\s+|\s+' 
        - '-+'   # -----------------------------
      separator: "|"
      keys: [speed, value, _, adj_speed]  # Items beyond these four will be ignored.
      action: store_multi
```
