### ISSUE TITLE
Using hidden key throws error.

### ISSUE THREAD

**Issue by coneheadusa** [hpc/pavilion2#337]
Using the example from the extracting-results document under the Wildcard Evaluations section found here:
[https://pavilion2.readthedocs.io/en/latest/tutorials/extracting_results.html#tutorials-extracting-results](url)
  ```
result_evaluate:
    # Get the average flops, given the flops value from each of our
    # node results files.
    avg_gflops: 'avg(per_file.*.gflops)'
    # The outliers function takes a list of values, a corresponding
    # list of names to associate with those values, and a number of
    # standard deviations from the mean to consider 'normal'.
    # It returns a mapping of 'name: stdev_from_mean' for items
    # that exceed that limit.
    # The first and second lists are guaranteed to be in corresponding
    # order.
    # hidden values is not working
    _outliers: 'outliers(per_file.*.flops, keys(per_file), 1.3)'
    #otlrs: 'outliers(per_file.*.gflops, keys(per_file), 1.3)'
    # Extract just the list of outlier names.
    outliers: 'keys(_outliers)'
```
I get this error:
 "Invalid key '_outliers' in CategoryElem called  result_evaluate. Key does not match expected  regular expression '^[a-zA-Z][a-zA-Z0-9_]+$'"   

Should the regex be changed to: '[a-zA-Z_][a-zA-Z0-9_]+$' ?
