### ISSUE TITLE
slurm_mpi scheduler should be just part of the slurm scheduler

### ISSUE THREAD

**Issue by francinelapid** [hpc/pavilion2#338]
Instead of having a whole separate scheduler dedicated to using `mpirun`, we should just have

```
scheduler: slurm
slurm:
    test_cmd: mpirun
    bind_to: socket
    num_nodes: 3
    tasks_per_node: 2
```

The overall code might be simpler and this will reduce redundancy in the host/mode configs.
