### ISSUE TITLE
Results missing files or directories behavior

### ISSUE THREAD

**Issue by Paul-Ferrell** [hpc/pavilion2#381]
An explicitly given, missing file, raises a FileExistsError - that should be caught, a message should be logged, but the result should just be set to None.
Similar behavior should occur when attempting to open a directory.

**Comment by Paul-Ferrell** [comment]
```yaml
result_parse:
  regex: 
    files: 'does-not-exist.txt'
    regex: 'foo'
```
