### ISSUE TITLE
Conditional Tests

### ISSUE THREAD

**Issue by Paul-Ferrell** [hpc/pavilion2#43]
This one is a bit brutal, but oh well. 

Test configs should have an `only_if` and `not_if` options. Each of these should take a mapping/dict, where the key name is a pavilion variable name, and the value is a list of possible values. Each of those possible values are in glob format (* - matches zero or more characters, ? - matches any one character), or use python regex's if you feel it's cleaner. For each of the key value pairs we'll be checking for matches. If the value of the pavilion variable for the key matches at least one of the value globs/regex's, then that key:value pair is a match. 

For the `only_if` option, the test should only run if all of the key:value pairs under it match. Otherwise, the test should be assigned a status of SKIPPED, and skipped. For the `not_if` options, the test should only run if none of the key:value pairs under it match. The status note should denote exactly why the test was skipped (if skipped for multiple reasons, have a generic message). 

Note that any valid pavilion variable should work as a key. 

```yaml
mytest:
  only_if:
    # Only run on fog
    sys.sys_name: fog
    # Only run on Tuesday's and Wednesday's
    date.day_of_week: [Tuesday, Wednesday]
  
  not_if:
    # Don't run for pflarr or jogas
    user: ['pflarr', 'jogas']
```

**Comment by Paul-Ferrell** [comment]
Calvin - You're the one who needs to do the actual work on this one. 
Francine - You're to help Calvin and get him oriented in the code base, and set up to deal with unit tests and such. Make sure he understands the coding standards and how we deal with stuff like exceptions. You should also serve as the first pass on his design decisions and for code reviews.

**Comment by francinelapid** [comment]
```
mytest:
  only_if:
    # Only run on fog
     - sys.sys_name: fog
    # Only run on Tuesday's and Wednesday's
    - date.day_of_week: [Tuesday, Wednesday]
  
  not_if:
    # Don't run for pflarr or jogas
    user: ['pflarr', 'jogas']
```
