### ISSUE TITLE
JSON result parser

### ISSUE THREAD

**Issue by Paul-Ferrell** [hpc/pavilion2#454]
Write a result parser to pull in the full contents of JSON files. 

 - It should have an 'exclude' option that lists keys (and everything under them) to exclude. 
 - It should have an 'include_only' option that lists the only keys to include.

Given a JSON file containing:
```json
{
  'foo': {
    'bar': [1, 3, 5]
    'baz': 6
  },
  'foo2': 37,
}
```

and a result parser config;
```yaml
mytest:
  result_parse:
    json:
      myjson:
        files: my.json
        include: ['foo']
        exclude: ['foo.baz']
```

The result json should contain:
```json
{
 'myjson': {
   'foo': {
     'bar': [1, 3, 5]
    }
}
```

- 'foo2' and everything under it was excluded because it wasn't in the 'include_only' line.
- 'foo.baz' was specifically exclude.

### Errors
Excluding or including something that doesn't exist should be an error. As should including/excluding something by key out of a non-dictionary, such 'foo.bar.whatever' (since 'foo.bar' is a list).
