### ISSUE TITLE
Variables ending in zero are truncated in use

### ISSUE THREAD

**Issue by jennfshr** [hpc/pavilion2#518]
```
#foo.yaml
base:
    subtitle: "silly reproducer"
    doc: |
        "this is to demonstrate a bug in variables"
    variables:
        var1: [ '1.90' ]

    build:
        cmds:
            - "echo var1 {{var1}}"
```
Trims trailing zeros that were deliberate from my variable.
```
$ pav log build 641
var1 1.9
```
