### ISSUE TITLE
Add min_tasks_per node schedule parameter

### ISSUE THREAD

**Issue by tygoetsch** [hpc/pavilion2#519]
This would allow the following functionality in a test:
```yaml
base:
  schedule:
    tasks_per_node: "{{sched.min_tasks_per}}"
```
