### ISSUE TITLE
Move mpirun options out of the Slurm plugin and into a generic config option.

### ISSUE THREAD

**Issue by Paul-Ferrell** [hpc/pavilion2#561]
This has two parts: 
1. Move the `mpirun_` prefixed config options (defined in the slurm scheduler plugin's config options) to an `mpirun` section in the general `schedule` section of the config. This should look like:

```yaml
mytest:
  schedule:
    mpirun_opts: 
      rank_by: cpus
      mca: ''
```

2. Move the `test_cmd` configuration of `mpirun` into it's own method in the base `SchedulerVariables` class. Then simply call that within the slurm section.
