### ISSUE TITLE
Module Wrappers via Test Configs

### ISSUE THREAD

**Issue by Paul-Ferrell** [hpc/pavilion2#567]
Add a new 'module_wrappers' section to the config, to allow for defining module wrappers as simple config sections, particularly in the host configs.

```yaml

module_wrappers:
  'name[/version]': 
    # If a version is given, loading that module will automatically specify that version.
    modules: 
      - '-foo'
      - 'bar'
    # An MODULENAME_VERSION environment variable will be set and usable automatically as well.
    env: 
      'CC': '$(which CC)'
```
