### ISSUE TITLE
Add support for configuring test_cmd on the raw scheduler

### ISSUE THREAD

**Issue by aebruno** [hpc/pavilion2#588]
Currently the raw scheduler returns empty string for `test_cmd`. Would be great if we could somehow override/configure this a on per test basis. For example, we have the following test:

```yaml
intelpong:
  summary: Intel MPI PingPong test.

  schedule:
    nodes: 2
    slurm:
      sbatch_extra: ['--constraint=IB']
      mpi_cmd: srun
  run:
    env:
      I_MPI_DEBUG: 4
    modules: ['intel/2022.00']
    cmds:
      - '{{sched.test_cmd}} IMB-MPI1 PingPong'
```

 This works great under slurm as `test_cmd` will be set to `srun`. However, testing this outside of slurm using the raw scheduler on a single node we need `test_cmd` set to `mpirun -np 2` otherwise the test fails. Reading through the docs it wasn't clear if there was a good way to achieve this? It would be great if we could override `test_cmd` for the raw scheduler, for example something like the following:

```yaml
intelpong:
  summary: Intel MPI PingPong test.

  schedule:
    nodes: 2
    raw:
      test_cmd: 'mpirun -np 2'
    slurm:
      sbatch_extra: ['--constraint=IB']
      mpi_cmd: srun
  run:
    env:
      I_MPI_DEBUG: 4
    modules: ['intel/2022.00']
    cmds:
      - '{{sched.test_cmd}} IMB-MPI1 PingPong'
```

Thanks!
