### ISSUE TITLE
`source_url` bug

### ISSUE THREAD

**Issue by smehta99** [hpc/pavilion2#631]
When using `source_url` in a pavilion test config, it downloads the source to the directory the command is executed and the build log tries to look for it in the `source_path:` resulting in an error:
```YAML
   build:
     source_url: https://github.com/LLNL/UMT/archive/refs/tags/v4.14.0.tar.gz
     source_download: "missing"
     source_path: umt/src
 ```
```bash
me@machine: ~/repo/pavilion2/examples/tutorials> ls -a
.  ..  activate.sh  .gitignore	hosts  pavilion.yaml  tests  test_src  working_dir
me@machine: ~/repo/pavilion2/examples/tutorials> pav run umt

Error making tests for series 's17'.
  Error creating test 'umt.base' in test set 'cmd_line'
    Could not create builder for test umt.base (run 10): Could not retrieve source from the given url
    'https://github.com/LLNL/UMT/archive/refs/tags/v4.14.0.tar.gz': ("Error writing download
    'https://github.com/LLNL/UMT/archive/refs/tags/v4.14.0.tar.gz' to file in
    '/yellow/users/smehta/repo/pavilion2/examples/tutorials/test_src/umt'.", FileNotFoundError(2, 'No such file
    or directory'))
me@machine: ~/repo/pavilion2/examples/tutorials> ls -a
.  ..  activate.sh  .gitignore	hosts  pavilion.yaml  tests  test_src  umt  working_dir
```
