### ISSUE TITLE
Conditional modes

### ISSUE THREAD

**Issue by Paul-Ferrell** [hpc/pavilion2#652]
1. Allow tests configs in the test to be used as modes?
  1. Require `_mode` prefix? 

```yaml
mytest:
  variables:
    compiler: 'intel'
  modes:
    _mode_intel: ['compiler == "intel"']

_mode_intel:
  variables:
    compiler_flags: '-a -b -c'
```
