### ISSUE TITLE
Add `when` clauses to variables (WIP)

### ISSUE THREAD

**Issue by Paul-Ferrell** [hpc/pavilion2#670]
Adding a `_when` clause to any complex variables.

```yaml

mytest:
  variables:
    input?:
      - 
      cc: ""
      cxx: ""
      threads: 1

 
    input:
      - _when: "sys_name == fireweasel"
        cc: cc
        cxx: CC
      - _when: "sys_name == iceferret"
        cc: cpp
        cxx: CPP
```

- Each matching `_when` item is _appended_.
