### ISSUE TITLE
Ability to use environment variables in results parse section

### ISSUE THREAD

**Issue by smehta99** [hpc/pavilion2#718]
I want to be able to do something like this:
```YAML
constant:
  compiler:
    const: "${COMPILER_NAME}/${COMPILER_VER}"
  mpi:
    const: "${MPI_NAME}/${MPI_VER}"
```
