### ISSUE TITLE
Updating the `create_files` stanza does not rebuild the test

### ISSUE THREAD

**Issue by smehta99** [hpc/pavilion2#799]
Going from this:
```YAML
    create_files:
      'test_dir/test.txt':
      - 'line 1'
      - 'line 2'
      - 'line 3'
      - 'line 4'
```
to this: 
```YAML
    create_files:
      'test.txt':
      - 'line 1'
      - 'line 2'
      - 'line 3'
      - 'line 4'
      - 'line 5'
```
does not re-generate the file in the correct location or update the existing file. I had to rebuilt the test by passing `-r` to pavilion command. Seems like updates to the `create_files:` stanza doesn't force rebuild the test like the other portions of the `build` stanza does.
