### ISSUE TITLE
`output_type: stdout` in command result parser causes RESULTS_ERROR

### ISSUE THREAD

**Issue by francinelapid** [hpc/pavilion2#815]
to recreate:

```
  result_parse:                                                                                                                                                                                                                                                                                                       
    command:                                                                                                                                                                                                                                                                                                          
      hello:                                                                                                                                                                                                                                                                                                          
        command: "echo hello"                                                                                                                                                                                                                                                                                         
        action: store                                                                                                                                                                                                                                                                                                 
        output_type: stdout                                                                                                                                                                                                                                                                                           
```

At first, `pav log results` is empty, but running `pav results --re-run <testid>` shows:
`TypeError: a bytes-like object is required, not 'str'`
